# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_customer_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
    ]
