# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0007_auto_20171012_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (3, 'On the way'), (1, 'Cooking'), (2, 'Ready')]),
        ),
    ]
