# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0009_auto_20171013_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the way'), (1, 'Cooking'), (4, 'Delivered'), (2, 'Ready')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sub_total',
            field=models.FloatField(),
        ),
    ]
