# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0011_auto_20171013_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sub_total',
            field=models.IntegerField(),
        ),
    ]
