# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0013_auto_20171014_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the way'), (2, 'Ready'), (4, 'Delivered'), (1, 'Cooking')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sub_total',
            field=models.FloatField(),
        ),
    ]
