# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0014_auto_20171014_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodtaskerapp.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the way'), (2, 'Ready'), (1, 'Cooking'), (4, 'Delivered')]),
        ),
    ]
